# Generated by Django 5.1.7 on 2025-03-28 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_rename_product_comment_proddfgdxgfcgvxcuct'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='proddfgdxgfcgvxcuct',
            new_name='product',
        ),
    ]
